vim.keymap.set({'n', 'v', 's', 'o'}, '<leader>gs', ':Git<CR>')
vim.keymap.set({'n', 'v', 's', 'o'}, '<leader>ga', ':Git add %<CR>')
vim.keymap.set({'n', 'v', 's', 'o'}, '<leader>gc', ':Git commit<CR>')
vim.keymap.set({'n', 'v', 's', 'o'}, '<leader>gca', ':Git commit --amend<CR>')
vim.keymap.set({'n', 'v', 's', 'o'}, '<leader>gce', ':Git commit --amend -C HEAD<CR>')
vim.keymap.set({'n', 'v', 's', 'o'}, '<leader>gp', ':Git push<CR>')
vim.keymap.set({'n', 'v', 's', 'o'}, '<leader>gpf', ':Git push --force<CR>')
vim.keymap.set({'n', 'v', 's', 'o'}, '<leader>gl', ':Git pull<CR>')
vim.keymap.set({'n', 'v', 's', 'o'}, '<leader>gll', ':Git log<CR>')
vim.keymap.set({'n', 'v', 's', 'o'}, '<leader>gd', ':Gvdiff<CR>')
vim.keymap.set({'n', 'v', 's', 'o'}, '<leader>gD', ':Ghdiff<CR>')

vim.keymap.set({'n', 'v', 's', 'o'}, '<F2>', ':Git<CR>')
vim.keymap.set({'n', 'v', 's', 'o'}, '<F3>', ':Git add %<CR>')
vim.keymap.set({'n', 'v', 's', 'o'}, '<F4>', ':Git commit<CR>')
